# Prod default
version: "3"
services:
  app:
    container_name: app
    # restart: always
    build: .
    image: ${USERNAME}/${IMAGE}
    env_file: 
      - .env
  db:
    image: postgres
    # restart: always
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}