# Dev Override
version: "3"
services:
  app:
    ports:
      - "8080:8080"
    environment: 
        NODE_ENV: "dev"
    # volumes: # hot reload: map <project dir>:<container dir>
    #     - .:/user/src/app
  mongo:
    # volumes:
    #   - ./data:/data/db 
    ports:
      - "27017:27017"