version: "2"
services:
  milky-way-service:
    container_name: milky-way-service
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    # volumes:
    #   - ./data:/data/db 
    ports:
      - "27017:27017"